### ISSUE TITLE
Problem with installing the addon.

### ISSUE THREAD

**Issue by DJan2404** [ArdCarraigh/Blender_SRT_JSON_Addon#1]
Hi, just wanted to say that when i'm trying to install the addon it doesn't appear in the addon list and when I do it with the source code zip file it does but I can't enable it for some reason.
![Zrzut ekranu (248)](https://github.com/ArdCarraigh/Blender_SRT_Addon/assets/72510707/2af09f72-27a4-46f5-ba00-dc9645dbb482)

**Comment by ArdCarraigh** [comment]
Disable it, restart Blender, re-enable it, that should fix it.
