### ISSUE TITLE
Grass textures not applied correctly inside redengine

### ISSUE THREAD

**Issue by ghost** [ArdCarraigh/Blender_SRT_JSON_Addon#2]
Very impressive addon, works nice with trees but I got problems when trying to create grass.
When checking "use as grass" the material texture is applied with wrong colors ingame but shown with correct colors in blender.
It only seems to happen when textures are applied to fronds, not to trunks while checking "use as grass".

I got no custom compiler for my old speedtree copy but this addon allows me to change shader settings (etc..) to be compatible with the redengine speedtree sdk integration.
When importing my own srt (grass) file into blender using this addon I do the following:

- adjust shader settings for redengine (deferred, smooth, unified shaders) 
- mark "use as grass"
- use dds textures for the material (also tried using redengine internal textures so the redengine is used to the correct compression format)
- import srt and dds textures in the same folder in redkit

I provide some example images and the files using a red/green/blue test texture (diffuse only, adding normal and specular doesnt solve the problem) so its easily distinguishable.

Inside blender:
![2  blender](https://github.com/user-attachments/assets/a88f3232-d1f5-4d51-a792-898fc8d8dd87)

Materials tab:
![3  blender materials tab](https://github.com/user-attachments/assets/dae907c2-a080-45b4-8820-ae5d1c0eb2a2)
![4  blender materials color set](https://github.com/user-attachments/assets/baa406c2-ec58-4fd6-b6f5-29ac83b1c867)
![5  blender materials others tab](https://github.com/user-attachments/assets/874ea843-3405-427c-a319-9c118b18cb85)

Ingame:
![6  ingame texture](https://github.com/user-attachments/assets/29d104ac-2a3b-428d-809d-5f26cfcd4cdc)

srt and texture file:
[srt and texture file.zip](https://github.com/user-attachments/files/16418230/srt.and.texture.file.zip)

edit: using blender 4.2 and latest addon version

**Comment by ArdCarraigh** [comment]
Hey,
Thank you for the very detailed bug report and for illustrations and exemple files to replicate the issue, this is the kind of bug report we appreciate.
Unfortunately, I am on vacations and I don't have a modding setup required to replicate nor investigate the issue.

Maybe you can try something, though.
Can you turn off the detail layer in the textures tab? You'll have to enable the branch geometry type before being able to turn it off. And then try to export again.
Keep me updated, thank you in advance.

Cheers

**Comment by ghost** [comment]
Hey there,
I tried disabling the detail layer using 3 different approaches (using different srt file copies) starting with the one you recommended :
- activating branch geometry -> disable detail layer -> export srt file
- import srt file -> close blender -> manually disable all "EDetailLayer" properties in the generated json file -> reimport the srt file into blender -> export the file with detail layer turned off
- disable the detail layer in speedtree (the detail layer was still enabled in blender for some reason)

None of the above ways worked so far. To be more precise everything still looks the same as before so nothing changed either.

Also I noticed the texture I provided might be misleading because the image outlines are generally applied correctly only the colors are not applied.
Here another example using some ingame texture for the grass (original grass_common_bob.dds):
![ingame](https://github.com/user-attachments/assets/5a9d3114-2eb7-48a4-acd2-e9cff0492096)

**Comment by ArdCarraigh** [comment]
Ok, so that shows that the textures get applied, that's good.
I did a bit of experiementation. And I managed to get the colors to show up. It doesn't seem to be a problem with the addon.
Just w3 grass shader being a bit tricky to work with.
My first advice would be to design normal and specular maps with your diffuse one (keep in mind the alpha of the specular should contain a transmission map).
And then you'll have to play with the shader settings (diffuse, ambient, transmission and specular). 
Unfortunately, the grass shader seems to vary greatly from what speedtree does in its own tool (which I based my work on), so don't expect the blender preview to be a good representation of what you will obtain in game.

**Comment by ghost** [comment]
Thanks for the hint I finally managed to get it working.
I found out that adjusting Transmission "View Influence" to 0.5 and "Shadow Brightness" to 0.04 brings back the colors even without using normal and specular maps.
I took those values from original ingame grass files.
Increasing either of those values only slightly already seems to make the texture color transition into some average color of the ground beneath it.
