### ISSUE TITLE
Addon unable to be installed on either 4.1.1 or 4.2.0

### ISSUE THREAD

**Issue by TheZokman** [ArdCarraigh/Blender_SRT_JSON_Addon#3]
Addon is not appearing in blender when installed, I went into the init file to change versions and that didn't fix it either. I also tried manually dragging into the scripts folder on both versions. I checked with another random 3rd party addon and it installed perfectly fine on both versions.

**Comment by ArdCarraigh** [comment]
You have to copy paste the directory called "io_mesh_srt" from the zip file to **C:\Program Files\Blender\4.2.0\4.2\scripts\addons_core** for Blender 4.2+ or **C:\Program Files\Blender\4.1.1\4.1\scripts\addons** for Blender 4.1.
**C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons** works too.

**Comment by TheZokman** [comment]
Thank you for your quick response, that worked perfectly.
